# Cluster Ip Service: react-srv-cluster-ip
apiVersion: v1
kind: Service
metadata:
  name: react-srv-clusterip
spec:
  type: ClusterIP # Implicit default value if not given
  selector:
    app: react
  ports:
    - name: react
      protocol: TCP
      port: 9002 #Vite react is hosted on port 5173 but we are using 9002 for the sake of simplicity
      targetPort: 9002
