apiVersion: skaffold/v4beta6
kind: Config
manifests:
  rawYaml:
    - ./auth/src/infra/k8s/**/*
    # - ./infra/k8s/ingress-nginx/*
build:
  local:
    push: false
  artifacts:
    - image: teclegacy/ticket/auth
      context: auth
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
