# Cluster Ip for event bus
apiVersion: v1
kind: Service
metadata:
  name: event-bus-clusterip
spec:
  type: ClusterIP
  selector:
    app: event-bus
  ports:
    - name: event-bus
      protocol: TCP
      port: 4006
      targetPort: 4006
