#  NodePort: posts-srv
apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: NodePort
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000
---
# Cluster Ip Service: posts-srv-cluster-ip
apiVersion: v1
kind: Service
metadata:
  name: posts-srv-clusterip
spec:
  type: ClusterIP # Implicit default value if not given
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000
